version: '3'
services:
  backend:
    build: ./backend
    image: backend:latest
    ports:
      - "3000:80"
  database:
    build: ./database
    image: database:latest
    ports:
      - "5431:5432"
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - "5000:5000"
